<?php
/**
 * @var string $user the logged in user, if any
 * @var callable $pathFor function to resolve router paths
 * @var callable $isCurrentPath function to check if a path is the current path
 * @var callable $srcUrlFor function to resolve resources
 *
 * @var string $path the current route path
 * @var string $origin_param url parameter that carries the $path
 * @var string $origin_path referrer path
 *
 * @var array $experiments all experiments (Experiment)
 * @var array $detectors detectors (Detector) with results per experiment
 * @var Experiment $experiment the selected experiment, if any
 * @var Detector $detector the selected detector, if any
 */
use MuBench\ReviewSite\Models\Detector;
use MuBench\ReviewSite\Models\Experiment;

?>
<div id="header">
    <div id="title">
        <a href="https://github.com/stg-tud/MUBench" title="MUBench Project">
            <img id="logo" src="<?= $srcUrlFor('assets/images/mubench_logo.png') ?>" />
        </a>
        <a href="<?= $pathFor('/') ?>" title="Home">Review<br/>Site</a>
    </div>

    <nav role="navigation">
        <ol>
            <?php $this_exp = isset($experiment) ? $experiment : null ?>
            <?php foreach ($experiments as $experiment): ?>
                <?php include "menu-experiment.phtml" ?>
            <?php endforeach ?>
            <?php $experiment = $this_exp ?>
            <li class="<?= strpos($path, '/stats') !== false ? "active" : "" ?>">
                <span>Statistics</span>
                <ul>
                    <li class="<?= $isCurrentPath('stats.tags') ? "active" : "" ?>">
                        <a href="<?= $pathFor('stats.tags') ?>">Tags</a>
                    </li>
                    <li class="<?= $isCurrentPath('stats.types') ? "active" : "" ?>">
                        <a href="<?= $pathFor('stats.types') ?>">Types</a>
                    </li>
                    <li class="<?= $isCurrentPath('stats.results') ? "active" : "" ?>">
                        <a href="<?= $pathFor('stats.results') ?>">Results</a>
                    </li>
                </ul>
            </li>
            <?php if($user) : ?>
                <li class="right <?= $isCurrentPath('overview') ? "active" : "" ?>">
                    <a href="<?= $pathFor('overview') ?>">My Reviews</a></li>
                <li class="right <?= $isCurrentPath('todo') ? "active" : "" ?>">
                    <a href="<?= $pathFor('todo') ?>">Open Reviews</a></li>
            <?php else: ?>
                <li class="right"><a href="<?= $loginPath ?>">Login</a></li>
            <?php endif; ?>
        </ol>
    </nav>
</div>
